# Generated by Django 4.0.3 on 2022-03-27 01:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionRecords',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('records', models.JSONField(blank=True, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(default='DEFAULT VALUE', max_length=254, unique=True)),
                ('status', models.CharField(default='Đang tiếp nhận', max_length=255)),
                ('approve', models.BooleanField(default=False)),
                ('assignment', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api_services.service')),
            ],
            options={
                'db_table': 'reception_records',
            },
        ),
        migrations.CreateModel(
            name='ApproveRecords',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_day', models.DateField(auto_now_add=True)),
                ('last_day', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('reception_records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_records', to='api_records.receptionrecords')),
            ],
            options={
                'db_table': 'approve_records',
            },
        ),
    ]
