# Generated by Django 4.0.3 on 2022-03-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionrecords',
            name='field',
        ),
    ]
