# Generated by Django 4.0.3 on 2022-03-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_records', '0002_remove_receptionrecords_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionrecords',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=254, unique=True),
        ),
    ]
