# Generated by Django 4.0.3 on 2022-03-27 01:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
