# Generated by Django 4.0.3 on 2022-03-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_departments', '0002_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
