# Generated by Django 4.0.3 on 2022-03-05 08:20

from django.db.models import Q
from django.db import migrations

from oauth2_provider.models import AbstractApplication
from core.settings import DEFAULT_CLIENT_SECRET, DEFAULT_CLIENT_ID, APP_NAME


def add_application(apps, schema_editor):
    Application = apps.get_model("api_oauth2", "Application")
    exist_app = Application.objects.filter(
        Q(name=APP_NAME), Q(client_id=DEFAULT_CLIENT_ID)
    ).exists()
    if not exist_app:
        Application.objects.create(
            client_id=DEFAULT_CLIENT_ID,
            client_type="confidential",
            authorization_grant_type="password",
            client_secret=DEFAULT_CLIENT_SECRET,
            name=APP_NAME,
            algorithm=AbstractApplication.RS256_ALGORITHM,
            scope="__all__",
        )


class Migration(migrations.Migration):
    dependencies = [
        ('api_oauth2', '0001_initial'),
    ]
    operations = [migrations.RunPython(
        add_application, migrations.RunPython.noop)]
