# Generated by Django 4.0.3 on 2022-03-27 01:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('decision_number', models.CharField(max_length=255)),
                ('type_procedure', models.CharField(blank=True, max_length=255, null=True)),
                ('code_DVCQG', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('method', models.JSONField(blank=True, null=True)),
                ('profile_composition', models.JSONField(blank=True, null=True)),
                ('object', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('receiving_address', models.CharField(blank=True, max_length=255, null=True)),
                ('juridical', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api_fields.field')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
