# Generated by Django 4.0.3 on 2022-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profile_composition',
        ),
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
