# Generated by Django 4.0.3 on 2022-03-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
