# Generated by Django 4.0.3 on 2022-03-08 02:35

from django.db import migrations


def initial_group_data(apps, schema_editor):
    group_model = apps.get_model("api_offices", "Group")
    group_first = group_model(name="Các đơn vị cấp ngành", parent_group=None)
    group_first.save()
    group_second = group_model(name="Các đơn vị cấp huyện", parent_group=None)
    group_second.save()
    group_third = group_model(name="các đơn vị cấp xã trực thuộc huyện", parent_group=group_second)
    group_third.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api_offices', '0001_initial'),
    ]

    operations = [migrations.RunPython(initial_group_data, migrations.RunPython.noop)]
