# Generated by Django 4.0.3 on 2022-03-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_offices', '0002_auto_20220308_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='nanme',
            new_name='name',
        ),
    ]
