# Generated by Django 4.0.3 on 2022-04-19 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_files', '0003_remove_servicecomponent_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_1', models.IntegerField()),
                ('question_2', models.IntegerField()),
                ('question_3', models.IntegerField()),
                ('question_4', models.IntegerField()),
                ('question_5', models.IntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluate', to='api_files.receptionrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
