# Generated by Django 4.0.3 on 2022-03-05 08:56

from django.db import migrations
from core.settings import SUPER_ADMIN_EMAIL, SUPER_ADMIN_PASSWORD
from django.contrib.auth.hashers import make_password


def add_user(apps, schema_editor):
    User = apps.get_model("api_users", "User")
    Role = apps.get_model("api_users", "Role")

    admin_role, created = Role.objects.get_or_create(
        name="Super Administrator",
        description="Unlimited resources access.",
        scope="super_admin",
    )

    exist_user = User.objects.filter(username=SUPER_ADMIN_EMAIL).exists()
    if not exist_user:
        User.objects.create(
            username=SUPER_ADMIN_EMAIL,
            email=SUPER_ADMIN_EMAIL,
            name="Super User",
            is_superuser=True,
            password=make_password(SUPER_ADMIN_PASSWORD),
        )
    super_user = User.objects.filter(username=SUPER_ADMIN_EMAIL).first()
    if not super_user:
        return
    super_user.roles.add(admin_role)
    super_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_user, migrations.RunPython.noop)]
