# Generated by Django 4.0.3 on 2022-03-07 03:53

from django.db import migrations


def add_role(apps, schema_editor):
    Role = apps.get_model("api_users", "Role")

    admin_role, created = Role.objects.get_or_create(
        name="Admin",
        description="Account admin",
        scope="admin",
    )


class Migration(migrations.Migration):
    dependencies = [
        ('api_users', '0003_auto_20220306_1414'),
    ]

    operations = [migrations.RunPython(add_role, migrations.RunPython.noop)]
