# Generated by Django 4.0.3 on 2022-04-16 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api_services.service')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ingredient', models.TextField()),
                ('attach', models.FileField(upload_to='')),
                ('original', models.IntegerField(default=0)),
                ('copy', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Xuất trình'), (2, 'Giao nộp')], default=2, max_length=1)),
                ('form', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api_files.file')),
            ],
            options={
                'db_table': 'files_details',
            },
        ),
    ]
