# Generated by Django 4.0.3 on 2022-04-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_services', '0003_remove_service_profile_composition_service_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pay_url', models.TextField(blank=True, default=None, null=True)),
                ('response_time', models.IntegerField(blank=True, default=None, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('result_code', models.CharField(blank=True, max_length=255, null=True)),
                ('deep_link', models.TextField(blank=True, default=None, null=True)),
                ('qr_code_url', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceptionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_sender', models.CharField(max_length=255)),
                ('code', models.CharField(default=None, max_length=10, null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(0, 'Chờ thanh toán'), (1, 'Đã gửi, đang tiếp nhận'), (2, 'Đã tiếp nhận, đang duyệt'), (3, 'Đã duyệt'), (4, 'Đã hủy')], default=0)),
                ('assignment', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='api_files.payment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='api_services.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ingredient', models.TextField()),
                ('original', models.IntegerField(default=0)),
                ('copy', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Xuất trình'), (2, 'Giao nộp')], default=2)),
                ('form', models.TextField(blank=True, null=True)),
                ('file_sample', models.FileField(upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api_services.service')),
            ],
            options={
                'db_table': 'files_details',
            },
        ),
        migrations.CreateModel(
            name='ReceptionRecordDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attach', models.FileField(upload_to='')),
                ('reception_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api_files.receptionrecord')),
                ('service_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_detail', to='api_files.servicecomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApproveRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('reception_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve', to='api_files.receptionrecord')),
                ('user_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
