# Generated by Django 4.0.3 on 2022-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='status',
            field=models.IntegerField(choices=[(1, 'Xuất trình'), (2, 'Giao nộp')], default=2, max_length=1),
        ),
    ]
