# Generated by Django 4.0.3 on 2022-04-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0004_alter_filedetails_status_receptionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionrecord',
            name='assignment',
            field=models.BooleanField(default=False),
        ),
    ]
