# Generated by Django 4.0.3 on 2022-04-16 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0005_alter_receptionrecord_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionrecord',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReceptionRecordDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attach', models.FileField(upload_to='')),
                ('file_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_files.filedetails')),
                ('reception_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_files.receptionrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
