# Generated by Django 4.0.3 on 2022-04-16 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_files', '0006_receptionrecord_content_receptionrecord_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionrecord',
            name='code',
            field=models.CharField(default='9KXX3W43GK', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ApproveRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('reception_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve', to='api_files.receptionrecord')),
                ('user_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
