# Generated by Django 4.0.3 on 2022-04-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0007_receptionrecord_code_approverecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionrecord',
            name='code',
            field=models.CharField(default='A5YR5REUX7', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='receptionrecorddetail',
            name='reception_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api_files.receptionrecord'),
        ),
    ]
