# Generated by Django 4.0.3 on 2022-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0008_alter_receptionrecord_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionrecord',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
