# Generated by Django 4.0.3 on 2022-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0010_receptionrecord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionrecord',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
