# Generated by Django 4.0.3 on 2022-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0011_alter_receptionrecord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
