# Generated by Django 4.0.3 on 2022-04-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0012_file_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionrecord',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receptionrecord',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chờ thanh toán'), (1, 'Đã gửi, đang tiếp nhận'), (2, 'Đã tiếp nhận, đang duyệt'), (3, 'Đã duyệt'), (4, 'Đã hủy')], default=0),
        ),
    ]
