# Generated by Django 4.0.3 on 2022-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0013_receptionrecord_payment_alter_receptionrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionrecord',
            name='code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
