# Generated by Django 4.0.3 on 2022-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0014_alter_receptionrecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionrecord',
            name='orderId',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
