# Generated by Django 4.0.3 on 2022-04-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0015_receptionrecord_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionrecord',
            name='orderId',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
