# Generated by Django 4.0.3 on 2022-04-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0016_alter_receptionrecord_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionrecord',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='receptionrecord',
            name='request_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
