# Generated by Django 4.0.3 on 2022-04-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_files', '0017_rename_orderid_receptionrecord_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionrecord',
            name='link_payment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
